version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=radmin
            - RABBITMQ_DEFAULT_PASS=r
        ports:
            - "5672:5672"

    worker:
        build:
            context: ../
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27017:27017"